name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:    
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy
    - name: Unit Tests
      run: MIRIFLAGS="-Zmiri-tree-borrows" cargo miri test --verbose refs::tests
    - name: UI Tests
      run: cargo test --verbose ui